### ISSUE TITLE
Will path references be supported?

### ISSUE THREAD

**Issue by rschindlauer** [ikalnitsky/sphinxcontrib-openapi#2]
I noticed that API specs with `$ref` path objects cause an error. Is that something that will be supported in the future?

**Comment by ikalnitsky** [comment]
@rschindlauer thanks for the feedback. Could you please provide an example so I can easily reproduce it? I'd really like to improve OpenApi support, and even tries to render examples in the future.

**Comment by rschindlauer** [comment]
Here is an example--although I didn't try to reproduce that exact one: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#paths-object-example

**Comment by ikalnitsky** [comment]
Well, `$ref`s in schemas aren't rendered yet, but they should not cause any errors. For instance, I do use `$ref` in the example spec here:

https://github.com/ikalnitsky/sphinxcontrib-openapi/blob/master/docs/specs/openapi.yml#L40

Maybe I got something wrong, and you meant some other case. Please, clarify.

**Comment by rschindlauer** [comment]
I think the issue is when the `description` is in the reference, not the element itself, like in this example (I believe this is valid swagger syntax):
```
swagger: "2.0"
info:
  title: Batcomputer API
  version: "1.0.0"
host: api.batcomputer.com
paths:
  /evidence:
    get:
      summary: List Evidence
      description: |
        Retrieves a list of evidence ever found by world's greatest
        detective and his family.
      responses:
        200:
          description: An array of evidence.
        default:
          $ref: '#/responses/default'
responses:
  default:
    description: Generic error response
```

This results in:
```
Exception occurred:
  File "/Users/.../sphinxcontrib/openapi.py", line 76, in _httpresource
    for line in response['description'].splitlines():
KeyError: 'description'
```

**Comment by ikalnitsky** [comment]
Yeah, that's indeed a valid syntax. Thanks for reporting! I'll fix it soon.

**Comment by thiyagaraj** [comment]
Hi @ikalnytskyi is this not pushed to pypi yet? We are still facing this error.. we did a pip install today(without giving a specific revision)

cc/ @zmagaw

**Comment by thiyagaraj** [comment]
@ikalnytskyi never mind, I just saw the note that it is "unreleased", any ETA on when 0.2.0 will be released?

**Comment by ikalnytskyi** [comment]
@thiyagaraj Sorry for the delay. I was hoping to implement more features before next release, but I was busy. I'll publish a new release later today.

**Comment by thiyagaraj** [comment]
Thank you @ikalnytskyi , your are helping others out, so take your time, didnt want to sound pushy 👍

**Comment by ikalnytskyi** [comment]
@thiyagaraj sorry for the delay once again :) I've pushed new version and now it's available on PyPi:

  https://pypi.python.org/pypi/sphinxcontrib-openapi

If you have any ideas how to improve this extension, please feel free to file an issue.

**Comment by AlexandraPosoldova** [comment]
I have the same issue and my swagger file has simple one line descriptions written in json.
Any updates on this? Thanks

**Comment by ikalnytskyi** [comment]
@AlexandraPosoldova could you please provide a little bit more details? I thought it's fixed and released.

**Comment by AlexandraPosoldova** [comment]
This is a code snipped from swagger file 2.0:
`"put": {
        "tags": [
          "FitMachines"
        ],
        "description": "Update detailed information of a specific FitMachine",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
          "name": "device_id",
          "in": "path",
          "description": "Device ID",
          "type": "integer",
          "required": true
        },
          {
            "in": "body",
            "name": "user",
            "schema": {
              "allOf":[
                {
                  "$ref": "#/definitions/NewDevice"
                },
                {
                  "$ref": "#/definitions/UpdateDevice"
                }
              ]

            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        },
        "security": [
          {
            "MovusAuth": []
          }
        ]
      },`

I refer to it in rat file as: `.. openapi:: ../swagger.json`
And get error message:
`Exception occurred:
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinxcontrib/openapi.py", line 107, in _httpresource
    for line in response['description'].splitlines():
KeyError: 'description'`

This is full log:
`# Sphinx version: 1.7.4
# Python version: 3.6.5 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#
#   building [html]: targets for 8 source files that are out of date
#
#   updating environment:
#
#   0 added, 1 changed, 0 removed
#
#   reading sources... [100%] overview
#
# Loaded extensions:
#   alabaster (0.7.10) from /Users/alex/anaconda3/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.7.4) from /Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinxcontrib.httpdomain (unknown version) from /Users/alex/anaconda3/lib/python3.6/site-packages/sphinxcontrib/httpdomain.py
#   sphinxcontrib.openapi (unknown version) from /Users/alex/anaconda3/lib/python3.6/site-packages/sphinxcontrib/openapi.py
#   sphinxcontrib.redoc (1.5.1) from /Users/alex/anaconda3/lib/python3.6/site-packages/sphinxcontrib/redoc.py
Traceback (most recent call last):
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 351, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/io.py", line 294, in read_doc
    pub.publish()
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinx/parsers.py", line 85, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinxcontrib/openapi.py", line 204, in run
    for line in openapi2httpdomain(spec, **self.options):
  File "/Users/alex/anaconda3/lib/python3.6/site-packages/sphinxcontrib/openapi.py", line 107, in _httpresource
    for line in response['description'].splitlines():
KeyError: 'description'
`
